PROGS_TESTWRITETIME_OBJS := testWriteTime.o
PROGS_TESTWRITETIME_OBJS := $(PROGS_TESTWRITETIME_OBJS:%=$(TDIR)/testWriteTime/%)
ALL_OBJS += $(PROGS_TESTWRITETIME_OBJS)

$(TDIR)/bin/testWriteTime : $(TSTART) $(PROGS_TESTWRITETIME_OBJS) $(TLIBC)

