PROGS_DAGGERMUTEX_OBJS := daggerMutex.o
PROGS_DAGGERMUTEX_OBJS := $(PROGS_DAGGERMUTEX_OBJS:%=$(TDIR)/daggerMutex/%)
ALL_OBJS += $(PROGS_DAGGERMUTEX_OBJS)

$(TDIR)/bin/daggerMutex : $(TSTART) $(PROGS_DAGGERMUTEX_OBJS) $(TLIBC)

